// const countries=[
//     {
//         id:0,
//         country:"India",
//         states:[
//             {
//                 idz:0,
//                 state:"Odisha",
//                 cities:[
//                     {
//                         idt:0,
//                         city:"Bhubaneswar",
//                     },{
//                         idt:1,
//                         city:"Cuttack",
//                     },{
//                         idt:2,
//                         city:"Chandikhole"
//                     }
//                 ]
//             },{
//                 idz:1,
//                 state:"Maharastra",
//                 cities:[
//                     {
//                         idt:0,
//                         city:"Mumbai",
//                     },{
//                         idt:1,
//                         city:"Pune",
//                     },{
//                         idt:2,
//                         city:"Nagpur"
//                     }
//                 ]
//             },{
//                 idz:2,
//                 state:"Jharkhand",
//                 cities:[
//                     {
//                         idt:0,
//                         city:"Dhanbad",
//                     },{
//                         idt:1,
//                         city:"Jamshedpur",
//                     },{
//                         idt:2,
//                         city:"Ranchi"
//                     }
//                 ]
//             }
//         ]
//     },{
//         id:1,
//         country:"America",
//         states:[
//             {
//                 idz:0,
//                 state:"Texas",
//                 cities:[
//                     {
//                         idt:0,
//                         city:"Houston",
//                     },{
//                         idt:1,
//                         city:"Dallas",
//                     },{
//                         idt:2,
//                         city:"Austin"
//                     }
//                 ]
//             },{
//                 idz:1,
//                 state:"New Mexico",
//                 cities:[
//                     {
//                         idt:0,
//                         city:"Albuquerque",
//                     },{
//                         idt:1,
//                         city:"Santa fe",
//                     },{
//                         idt:2,
//                         city:"Silver City"
//                     }
//                 ]
//             },{
//                 idz:2,
//                 state:"California",
//                 cities:[
//                     {
//                         idt:0,
//                         city:"Los Angeles",
//                     },{
//                         idt:1,
//                         city:"San Fransisco",
//                     },{
//                         idt:2,
//                         city:"San diego"
//                     }
//                 ]
//             }
//         ]
//     },{
//         id:2,
//         country:"Pakistan",
//         states:[
//             {
//                 idz:0,
//                 state:"Punjab",
//                 cities:[
//                     {
//                         idt:0,
//                         city:"Lahore",
//                     },{
//                         idt:1,
//                         city:"Multan",
//                     },{
//                         idt:2,
//                         city:"Faisalabad"
//                     }
//                 ]
//             },{
//                 idz:1,
//                 state:"Balochistan",
//                 cities:[
//                     {
//                         idt:0,
//                         city:"Quetta",
//                     },{
//                         idt:1,
//                         city:"Turbat",
//                     },{
//                         idt:2,
//                         city:"Chaman"
//                     }
//                 ]
//             },{
//                 idz:2,
//                 state:"Sindh",
//                 cities:[
//                     {
//                         idt:0,
//                         city:"Karachi",
//                     },{
//                         idt:1,
//                         city:"Hyderabad",
//                     },{
//                         idt:2,
//                         city:"Larkana"
//                     }
//                 ]
//             }
//         ]
//     } 
// ]

// export {countries};